apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2024-06-29T16:56:06Z","labels":{"app":"jupyter-app"},"name":"jupyter-svc","namespace":"jupyter","resourceVersion":"541","uid":"dcdf37b7-45af-4f15-9761-5ddb30beddec"},"spec":{"clusterIP":"10.102.10.182","clusterIPs":["10.102.10.182"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"nodePort":30000,"port":8888,"protocol":"TCP","targetPort":8888}],"selector":{"app":"jupyter-pods"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2024-06-29T16:56:06Z"
  labels:
    app: jupyter-app
  name: jupyter-svc
  namespace: jupyter
  resourceVersion: "2008"
  uid: dcdf37b7-45af-4f15-9761-5ddb30beddec
spec:
  clusterIP: 10.102.10.182
  clusterIPs:
  - 10.102.10.182
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: jupyter-pods
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
